name: 'Run Django Tests Workflow'
description: 'Runs Django unit tests with configurable services and versions'
author: 'Prince Kumar <pkumar@onemindservices.com>'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'

  enable-postgresql:
    description: 'Enable PostgreSQL service'
    required: false
    default: 'true'

  enable-redis:
    description: 'Enable Redis service'
    required: false
    default: 'true'

  enable-minio:
    description: 'Enable MinIO service'
    required: false
    default: 'false'

  enable-tsdb:
    description: 'Enable InfluxDB (TSDB) service'
    required: false
    default: 'false'

  postgresql-version:
    description: 'PostgreSQL version'
    required: false
    default: 'latest'

  redis-version:
    description: 'Redis version'
    required: false
    default: 'latest'

  minio-version:
    description: 'MinIO version'
    required: false
    default: 'latest'

  influxdb-version:
    description: 'InfluxDB version'
    required: false
    default: 'latest'

  runner:
    description: 'GitHub runner to use'
    required: false
    default: 'ubuntu-22.04-sh'

runs:
  using: "composite"
  steps:
    - name: Run Django Tests Workflow
      uses: ./.github/workflows/django-tests.yml
      with:
        python-version: ${{ inputs.python-version }}
        enable-postgresql: ${{ inputs.enable-postgresql }}
        enable-redis: ${{ inputs.enable-redis }}
        enable-minio: ${{ inputs.enable-minio }}
        enable-tsdb: ${{ inputs.enable-tsdb }}
        postgresql-version: ${{ inputs.postgresql-version }}
        redis-version: ${{ inputs.redis-version }}
        minio-version: ${{ inputs.minio-version }}
        influxdb-version: ${{ inputs.influxdb-version }}
        runner: ${{ inputs.runner }}
