name: 'Pre-commit Checks'
description: 'Run pre-commit hooks for code quality and linting'
author: 'Prince Kumar <pkumar@onemindservices.com>'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  runner:
    description: 'GitHub runner to use'
    required: false
    default: 'ubuntu-22.04-sh'

runs:
  using: "composite"
  steps:
    - name: Run pre-commit hooks
      uses: ./.github/workflows/pre-commit.yml
      with:
        runner: ${{ inputs.runner }}
        python-version: ${{ inputs.python-version }}
