name: 'yq - portable yaml processor'
description: 'create, read, update, delete, merge, validate and do more with yaml'
branding:
  icon: command
  color: gray-dark
inputs:
  cmd:
    description: 'The Command which should be run'
    required: true
outputs:
  result:
    description: "The complete result from the yq command being run"
runs:
  using: 'docker'
  image: 'docker://registry.onemindservices.com/docker.io/mikefarah/yq@sha256:adf65ee05593fa49dcb9f89cedb0417b90065465e9556d468d3e1fa256c1c0da'
  args:
    - ${{ inputs.cmd }}

