name: ESLint Check
description: Run ESLint and fail on any issues (warnings are errors).

inputs:
  node-version:
    description: Node.js version to use
    required: false
    default: '22.x'
  working-directory:
    description: Directory to run ESLint in
    required: false
    default: '.'
  config:
    description: Path to ESLint config file (e.g., eslint.config.mjs)
    required: false
    default: 'eslint.config.mjs'
  eslint-args:
    description: Additional ESLint args or target paths
    required: false
    default: '.'
  version:
    description: Optional ESLint version or dist-tag to run via npx (e.g., '9.9.0' or 'latest')
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Detect Package Manager
      id: pm
      uses: Onemind-Services-LLC/actions/actions/detect-package-manager@master
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: Setup Node
      uses: Onemind-Services-LLC/actions/actions/node-install-build@master
      with:
        package-manager: ${{ steps.pm.outputs.package-manager }}
        node-version: ${{ inputs.node-version }}
        working-directory: ${{ inputs.working-directory }}
        install: 'false'
        build: 'false'

    - name: Run ESLint
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set -euo pipefail
        cfg='${{ inputs.config }}'
        extra_cfg=()
        if [[ -n "$cfg" ]]; then
          if [[ -f "$cfg" ]]; then
            extra_cfg=("--config" "$cfg")
          else
            echo "::notice::ESLint config '$cfg' not found in $PWD; running with ESLint defaults/autodiscovery."
          fi
        fi
        pkg="eslint"
        if [[ -n "${{ inputs.version }}" ]]; then
          pkg="eslint@${{ inputs.version }}"
        fi
        echo "+ npx --yes -p $pkg --max-warnings=0 ${extra_cfg[*]} ${{ inputs.eslint-args }}"
        npx --yes -p "$pkg" --max-warnings=0 "${extra_cfg[@]}" ${{ inputs.eslint-args }}
