name: Code Coverage Summary
description: Generate a coverage summary from Cobertura XML and post a sticky PR comment using irongut/CodeCoverageSummary and marocchino/sticky-pull-request-comment (pinned).

inputs:
  path:
    description: Path or glob to coverage XML file
    required: true
    default: 'coverage.xml'
  working-directory:
    description: Optional directory to resolve relative coverage paths
    required: false
    default: '.'
  minimum-coverage:
    description: Minimum coverage percentage threshold
    required: false
    default: '80'
  fail-below-threshold:
    description: Fail when below minimum coverage
    required: false
    default: 'true'
  show-branch:
    description: Show branch coverage column
    required: false
    default: 'true'
  report-name:
    description: Unique name for the report/comment
    required: false
    default: 'Code Coverage Summary'
  pull-request-number:
    description: Pull request number when not using pull_request trigger
    required: false
    default: ''
  github-token:
    description: GitHub token to use for commenting (defaults to github.token)
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Generate Code Coverage Summary
      uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
      with:
        filename: ${{ format('{0}/{1}', inputs.working-directory, inputs.path) }}
        badge: true
        format: markdown
        output: both
        fail_below_min: ${{ inputs.fail-below-threshold }}
        hide_branch_rate: ${{ inputs.show-branch == 'false' }}
        hide_complexity: 'false'
        thresholds: '${{ inputs.minimum-coverage }} ${{ inputs.minimum-coverage }}'

    - name: Add Coverage PR Comment
      if: ${{ (github.event_name == 'pull_request' || inputs.pull-request-number != '') && inputs.github-token != '' }}
      uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2.9.4
      with:
        path: code-coverage-results.md
        only_update: true
        header: ${{ inputs.report-name }}
        number: ${{ inputs.pull-request-number }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
