name: 'NetBox Plugin Testing'
description: 'Runs tests for NetBox plugins with appropriate infrastructure'
author: 'Prince Kumar <pkumar@onemindservices.com>'

inputs:
  plugin-name:
    description: 'The name of the NetBox plugin (also used as the directory name)'
    required: true
  netbox-version:
    description: 'NetBox version to use (tag name, e.g., v4.2.9)'
    required: true
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  runner:
    description: 'GitHub runner to use'
    required: false
    default: 'ubuntu-22.04-sh'

runs:
  using: "composite"
  steps:
    - name: Run Tests Workflow
      uses: ./.github/workflows/netbox-plugin-tests.yml
      with:
        runner: ${{ inputs.runner }}
        plugin-name: ${{ inputs.plugin-name }}
        python-version: ${{ inputs.python-version }}
        netbox-version: ${{ inputs.netbox-version }}
