name: 'NetBox Plugin Testing'
description: 'Runs tests for NetBox plugins with appropriate infrastructure'
author: 'Prince Kumar <pkumar@onemindservices.com>'

inputs:
  plugin_name:
    description: 'The name of the NetBox plugin (also used as the directory name)'
    required: true
  netbox_version:
    description: 'NetBox version to use (tag name, e.g., v4.2.9)'
    required: true
  python_version:
    description: 'Python version to use'
    required: false
    default: '3.12'

runs:
  using: "composite"
  steps:
    - name: Run Tests Workflow
      uses: ./.github/workflows/netbox-plugin-tests.yml
      with:
        plugin_name: ${{ inputs.plugin_name }}
        python_version: ${{ inputs.python_version }}
        netbox_version: ${{ inputs.netbox_version }}
