name: 'Run Pytest Workflow'
description: 'Runs Pytest tests with configurable Python version and runner'
author: 'Prince Kumar <pkumar@onemindservices.com>'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'

  runner:
    description: 'GitHub runner to use'
    required: false
    default: 'ubuntu-22.04-sh'

runs:
  using: "composite"
  steps:
    - name: Run Django Tests Workflow
      uses: ./.github/workflows/pytest.yml
      with:
        python-version: ${{ inputs.python-version }}
        runner: ${{ inputs.runner }}
