name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    if: github.repository == 'Onemind-Services-LLC/actions'
    runs-on: ubuntu-22.04-sh
    steps:
      - name: Create App Token
        id: repo-token
        uses: Onemind-Services-LLC/actions/actions/create-repo-token@master
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: Onemind-Services-LLC
          github-token: ${{ github.actor == 'dependabot[bot]' && github.token || '' }}

      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: Onemind-Services-LLC/actions/actions/python-setup-install@master
        with:
          github-token: ${{ steps.repo-token.outputs.token }}

      - name: Run yamllint
        uses: Onemind-Services-LLC/actions/actions/yamllint@master
