name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    name: CI
    if: github.repository == 'Onemind-Services-LLC/actions'
    runs-on: ubuntu-22.04-sh
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: Onemind-Services-LLC/actions/actions/python-setup-install@master

      - name: Run yamllint
        uses: Onemind-Services-LLC/actions/actions/yamllint@master
