name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    if: github.repository == 'Onemind-Services-LLC/actions'
    runs-on: ubuntu-22.04-sh
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: Onemind-Services-LLC/actions/actions/python-setup-install@master

      - name: Run yamllint
        uses: Onemind-Services-LLC/actions/actions/yamllint@master

  update-org-actions-latest-sha:
    name: Update Org Variable ACTIONS_LATEST_SHA
    if: github.repository == 'Onemind-Services-LLC/actions' && github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    needs: lint
    runs-on: ubuntu-22.04-sh
    permissions:
      contents: read
    steps:
      - name: Create org-scoped token via GitHub App
        id: repo-token
        uses: Onemind-Services-LLC/actions/actions/create-repo-token@master
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Upsert ACTIONS_LATEST_SHA
        env:
          TOKEN: ${{ steps.repo-token.outputs.token }}
          ORG: ${{ github.repository_owner }}
          SHA: ${{ github.sha }}
        run: |
          set -euo pipefail
          if [ -z "${TOKEN:-}" ]; then
            echo "Missing token from create-repo-token action" >&2
            exit 1
          fi

          base_url="https://api.github.com/orgs/${ORG}/actions/variables"

          # Check if variable exists
          status=$(curl -sS -o /dev/null -w "%{http_code}" \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "${base_url}/ACTIONS_LATEST_SHA")

          if [ "$status" = "200" ]; then
            # Update existing variable (PATCH)
            curl -sS -f -X PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${TOKEN}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d "{\"name\":\"ACTIONS_LATEST_SHA\",\"value\":\"${SHA}\"}" \
              "${base_url}/ACTIONS_LATEST_SHA" >/dev/null
          elif [ "$status" = "404" ]; then
            # Create variable (POST)
            curl -sS -f -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${TOKEN}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d "{\"name\":\"ACTIONS_LATEST_SHA\",\"value\":\"${SHA}\",\"visibility\":\"all\"}" \
              "${base_url}" >/dev/null
          else
            echo "Unexpected status checking variable: ${status}. The GitHub App token may lack org permissions for variables." >&2
            exit 1
          fi
