name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run yamllint
        uses: Onemind-Services-LLC/actions/actions/yamllint@master
