name: Cypress E2E Tests

on:
  workflow_call:
    inputs:
      runs-on:
        description: GitHub runner label
        required: false
        default: 'ubuntu-22.04-sh'
        type: string
      browsers:
        description: JSON array of browsers (e.g., ["chrome","edge","firefox"]) 
        required: false
        default: '["chrome","edge","firefox"]'
        type: string
      start:
        description: Command to start the app/server for E2E
        required: true
        type: string
      wait-on:
        description: URL(s) to wait on before running tests (comma or space separated)
        required: true
        type: string
      wait-on-timeout:
        description: Timeout (seconds) for wait-on
        required: false
        default: '300'
        type: string
      registry-url:
        description: NPM registry URL for private packages
        required: false
        default: 'https://npm.pkg.github.com'
        type: string
      registry-scope:
        description: NPM scope used for auth (e.g., @onemind-services-llc)
        required: false
        default: '@onemind-services-llc'
        type: string
      working-directory:
        description: Directory containing the project to test
        required: false
        default: '.'
        type: string
      node-version:
        description: Node.js version to use
        required: false
        default: '22.x'
        type: string
      app-id:
        description: GitHub App ID for generating installation token (falls back to vars.APP_ID if omitted)
        required: false
        type: string
    secrets:
      private-key:
        description: GitHub App private key (PEM) used to mint installation tokens
        required: true

permissions:
  contents: read

jobs:
  e2e:
    name: End To End Tests
    runs-on: ${{ inputs.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        browser: ${{ fromJSON(inputs.browsers) }}
    steps:
      - name: Create App Token
        id: repo-token
        uses: Onemind-Services-LLC/actions/actions/create-repo-token@master
        with:
          app-id: ${{ inputs.app-id }}
          private-key: ${{ secrets.private-key }}
          owner: Onemind-Services-LLC

      - name: Checkout
        uses: actions/checkout@v5

      - name: Run Cypress e2e tests
        uses: Onemind-Services-LLC/actions/actions/cypress-test@master
        with:
          component: false
          start: ${{ inputs.start }}
          wait-on: ${{ inputs.wait-on }}
          wait-on-timeout: ${{ inputs.wait-on-timeout }}
          browser: ${{ matrix.browser }}
          registry-scope: ${{ inputs.registry-scope }}
          registry-url: ${{ inputs.registry-url }}
          npm-token: ${{ steps.repo-token.outputs.token }}
          working-directory: ${{ inputs.working-directory }}
          node-version: ${{ inputs.node-version }}
