name: ESLint Check

on:
  workflow_call:
    inputs:
      runs-on:
        description: Runner label
        required: false
        default: ubuntu-22.04-sh
        type: string
      node-version:
        description: Node.js version
        required: false
        default: '22.x'
        type: string
      working-directory:
        description: Directory to run ESLint in
        required: false
        default: '.'
        type: string
      eslint-args:
        description: Additional ESLint args or target paths
        required: false
        default: '.'
        type: string

permissions:
  contents: read

jobs:
  eslint:
    name: ESLint Check
    runs-on: ${{ inputs.runs-on }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: Onemind-Services-LLC/actions/actions/npm-install-build@master
        with:
          node-version: ${{ inputs.node-version }}
          install: true
          build: false

      - name: Run ESLint
        run: npx eslint --max-warnings=0 ${{ inputs.eslint-args }}
