name: JavaScript Quality Checks

on:
  workflow_call:
    inputs:
      runs-on:
        description: Runner label
        required: false
        default: ubuntu-22.04-sh
        type: string
      node-version:
        description: Node.js version
        required: false
        default: '22.x'
        type: string
      working-directory:
        description: Directory to run checks in
        required: false
        default: '.'
        type: string
      patterns:
        description: Glob for Prettier check
        required: false
        default: '**/*.+(js|jsx|ts|tsx|json|css|scss)'
        type: string
      eslint-args:
        description: Additional ESLint args or target paths
        required: false
        default: '.'
        type: string

permissions:
  contents: read

jobs:
  quality:
    name: JavaScript Quality Checks
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Prettier Check
        uses: Onemind-Services-LLC/actions/actions/prettier-check@master
        with:
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ inputs.working-directory }}
          patterns: ${{ inputs.patterns }}

      - name: ESLint Check
        uses: Onemind-Services-LLC/actions/actions/eslint-check@master
        with:
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ inputs.working-directory }}
          eslint-args: ${{ inputs.eslint-args }}

      - name: Browserslist Lock Check
        uses: Onemind-Services-LLC/actions/actions/browserslist-lock-check@master
        with:
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ inputs.working-directory }}
