name: NetBox Plugin Tests

on:
  workflow_call:
    inputs:
      plugin-name:
        description: 'The name of the NetBox plugin, eg: netbox_secrets'
        required: true
        type: string
      netbox-version:
        description: 'NetBox version to use, eg: v4.3.0'
        required: true
        type: string
      python-version:
        description: 'Python version to use, eg: 3.12'
        required: false
        default: '3.12'
        type: string
      runner:
        description: 'GitHub runner to use'
        required: false
        type: string
        default: 'ubuntu-22.04-sh'

env:
  NETBOX_WORKING_DIRECTORY: netbox

permissions:
  contents: read

jobs:
  test:
    name: Run Tests
    runs-on: ${{ inputs.runner }}

    services:
      redis:
        image: registry.onemindservices.com/docker.io/library/redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

      postgres:
        image: registry.onemindservices.com/docker.io/library/postgres:17-alpine
        env:
          POSTGRES_USER: netbox
          POSTGRES_PASSWORD: netbox
          POSTGRES_DB: netbox
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Create App Token
        id: repo-token
        uses: Onemind-Services-LLC/actions/actions/create-repo-token@master
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout Plugin Repository
        uses: actions/checkout@v4
        with:
          path: ${{ inputs.plugin-name }}

      - name: Checkout NetBox Repository
        uses: actions/checkout@v4
        with:
          repository: "netbox-community/netbox"
          path: netbox
          ref: ${{ inputs.netbox-version }}

      - name: Setup NetBox Requirements
        uses: Onemind-Services-LLC/actions/actions/python-setup-install@master
        with:
          python-version: ${{ inputs.python-version }}
          working-directory: ${{ env.NETBOX_WORKING_DIRECTORY }}

      - name: Setup Plugin Requirements
        uses: Onemind-Services-LLC/actions/actions/python-setup-install@master
        with:
          python-version: ${{ inputs.python-version }}
          working-directory: ${{ inputs.plugin-name }}
          github-token: ${{ steps.repo-token.outputs.token }}
          extra-install-commands: |
            sudo apt-get update && sudo apt-get install -y libpq-dev
            pip install -e .

      - name: Configure NetBox
        working-directory: ${{ env.NETBOX_WORKING_DIRECTORY }}
        run: |
          ln -sf $(pwd)/../${{ inputs.plugin-name }}/testing_configuration/configuration.py netbox/netbox/configuration.py

      - name: Run Tests
        uses: Onemind-Services-LLC/actions/actions/django-test-runner@master
        with:
          working-directory: ${{ env.NETBOX_WORKING_DIRECTORY }}/netbox
          django-settings-module: netbox.configuration
          test-args: ${{ inputs.plugin-name }}.tests --parallel
