name: NetBox Plugin Tests

on:
  workflow_call:
    inputs:
      plugin-name:
        description: 'The name of the NetBox plugin, eg: netbox_secrets'
        required: true
        type: string
      netbox-version:
        description: 'NetBox version to use, eg: v4.3.0'
        required: true
        type: string
      python-version:
        description: 'Python version to use, eg: 3.12'
        required: false
        default: '3.12'
        type: string
      runner:
        description: 'GitHub runner to use'
        required: false
        type: string
        default: 'ubuntu-22.04-sh'

jobs:
  test:
    name: Run Tests
    runs-on: ${{ inputs.runner }}

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: netbox
          POSTGRES_PASSWORD: netbox
          POSTGRES_DB: netbox
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Create App Token
        id: repo-token
        uses: Onemind-Services-LLC/actions/actions/create-repo-token@master
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev

      - name: Checkout Plugin Repository
        uses: actions/checkout@v4
        with:
          path: ${{ inputs.plugin-name }}

      - name: Checkout NetBox Repository
        uses: actions/checkout@v4
        with:
          repository: "netbox-community/netbox"
          path: netbox
          ref: ${{ inputs.netbox-version }}

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'

      - name: Install Plugin Dependencies
        working-directory: ${{ inputs.plugin-name }}
        run: |
          echo machine github.com login ${{ steps.repo-token.outputs.token }} > ~/.netrc
          
          python -m pip install --upgrade pip
          pip install -e .  # Install in development mode
          
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Install NetBox Core Dependencies
        working-directory: netbox
        run: |
          pip install -r requirements.txt

      - name: Configure NetBox
        working-directory: netbox
        run: |
          ln -sf $(pwd)/../${{ inputs.plugin-name }}/testing_configuration/configuration.py netbox/netbox/configuration.py

      - name: Validate Database Migrations
        working-directory: netbox
        run: python netbox/manage.py makemigrations --check

      - name: Run Tests
        working-directory: netbox
        run: python netbox/manage.py test ${{ inputs.plugin-name }}.tests --parallel
