name: Pre-commit Checks

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use, eg: 3.12'
        required: false
        default: '3.12'
        type: string
      runner:
        description: 'GitHub runner to use'
        required: false
        type: string
        default: 'ubuntu-22.04-sh'

jobs:
  pre-commit:
    name: Run pre-commit hooks
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: pip

      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd