name: Pre-commit Checks

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use, eg: 3.12'
        required: false
        default: '3.12'
        type: string
      runs-on:
        description: 'GitHub runner to use'
        required: false
        type: string
        default: 'ubuntu-22.04-sh'
      app-id:
        description: GitHub App ID for generating installation token (falls back to vars.APP_ID if omitted)
        required: false
        type: string
    secrets:
      private-key:
        description: GitHub App private key (PEM) used to mint installation tokens
        required: false

jobs:
  pre-commit:
    name: Run pre-commit hooks
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Create App Token
        id: repo-token
        uses: Onemind-Services-LLC/actions/actions/create-repo-token@master
        with:
          app-id: ${{ inputs.app-id }}
          private-key: ${{ secrets.private-key }}
          owner: Onemind-Services-LLC
          github-token: ${{ github.actor == 'dependabot[bot]' && github.token || secrets.GIT_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: pip

      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd
